apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: jsonserve
  name: jsonserve
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jsonserve
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: jsonserve
    spec:
      containers:
        - image: prathammanocha/jsonserveapp:v1.0
          name: jsonserve
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
